### ISSUE TITLE
Doesnt work trough the exe

### ISSUE THREAD

**Issue by M4RCK5** [SegoCode/swd#1]
Im trying to download this mod for example https://steamcommunity.com/sharedfiles/filedetails/?id=2478838270 trought the app and it dowsnt work, but when i try to do it trough the webpage it doesnt give any problem.

**Comment by SegoCode** [comment]
Hi, 
what is the console output ?

**Comment by SegoCode** [comment]
Found the problem, api endpoint change.

**Comment by SegoCode** [comment]
Publish new release, everything works fine now!

Thx!

**Comment by M4RCK5** [comment]
Sorry for late reply, it works witouth problems now, thank u a lot, this its very usefull :)
