### ISSUE TITLE
It seems that the tool isnt working again :(

### ISSUE THREAD

**Issue by M4RCK5** [SegoCode/swd#2]
[←[36mINFO←[0m]  CHEKING IF THE GAME IS AVAILABLE FOR STEAM WORKSHOP DOWNLOADS . . .
[←[31mERR←[0m]  GAME NOT AVAILABLE OR SERVER IS DOWN, CODE RESPONSE: 400
Presione una tecla para continuar . . .

I was trying to download this mod https://steamcommunity.com/sharedfiles/filedetails/?id=1870630263 , from the webpage i can download it witouth problems like the last time.

**Comment by SegoCode** [comment]
Well, I have check it quickly and again the endpoints changed, but this time also the structure of the request, is a chaos and inefficient, not follow any of the API good practices...

This change is going to take me a little longer...
Thanks for the warning💕

**Comment by SegoCode** [comment]
The guys behind steamworkshopdownloader.io do tricky things to prevent third parties consume their API.

Nothing I can't do reverse engineering, but there are no guarantees that change the way of working every month, maybe a different approach... launch fake browser and capture the download...

Seriously, under the hood looks an inefficient chaos api, they could even put a payment model to consume the api externally, if any of steamworkshopdownloader.io dev is reading this contact me I could help with the project.

Well... I don't feel motivated to continue maintaining this repo, sorry

**Comment by nguyenvancaokyfpt** [comment]
I fixed it for you, and now it works perfectly
[Pull requests](https://github.com/SegoCode/swd/pull/3)

**Comment by SegoCode** [comment]
Well... that was unexpected, i appreciate it a lot, tomorrow I will publish the new release 💕

**Comment by SegoCode** [comment]
New release published, looks everything works perfectly, thank you again @nguyenvancaokyfpt
