### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by Be1zebub** [SegoCode/swd#4]
I used swd to batch download 176 addons from the workshop, with a wait of 10 seconds between downloads.
Only 100 addons were successfully downloaded, 76 gave this error.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x96b9d2]

goroutine 1 [running]:
main.main()
        C:/Users/SegoCode/Documents/GitHub/swd/swd.go:96 +0x132
```
it was running via exe file from the releases.

**Comment by SegoCode** [comment]
Hi, 
That error appears when there is a connection problem, something has happened when trying to connect to github server or steamworkshopdownloader.io... i need to catch nil err in future versions...

**I've tested and it seems to be working fine**, maybe it's a 429 Too Many Requests to the github server to check the version or steamworkshopdownloader.io if you're running it in some kind of loop. ~~or firewall problems, or internet problems~~

In future versions I will make it more verbose, to show the errors correctly. 

Share your batch file, maybe we can make a cool script together

**Comment by Be1zebub** [comment]
i use luvit for batch downloading
[download.lua.txt](https://github.com/SegoCode/swd/files/7898949/download.lua.txt)
its just a 2 min script, i wanted to download all the addons I subscribed to - without spending a lot of time developing a tool for this :)

**Comment by Be1zebub** [comment]
btw please add more supported params - like `--downloadFormat gmaextract` 
this would be very useful for some games, for example, for the Garrys mod, such a payload makes the steamworkshopdownloader.io automatically unpack the `.gma`
`{"publishedFileId":282498239,"collectionId":null,"hidden":false,"downloadFormat":"gmaextract","autodownload":false}`

**Comment by SegoCode** [comment]
> i use luvit for batch downloading [download.lua.txt](https://github.com/SegoCode/swd/files/7898949/download.lua.txt) its just a 2 min script, i wanted to download all the addons I subscribed to - without spending a lot of time developing a tool for this :)

I think the problem is github version check, break when you do many request without token, i make it optional

**Comment by SegoCode** [comment]
[New release](https://github.com/SegoCode/swd/releases/tag/1.5) probably fix the issue
