### ISSUE TITLE
Please add more supported params

### ISSUE THREAD

**Issue by SegoCode** [SegoCode/swd#5]
btw please add more supported params - like `--downloadFormat gmaextract` 
this would be very useful for some games, for example, for the Garrys mod, such a payload makes the steamworkshopdownloader.io automatically unpack the `.gma`
`{"publishedFileId":282498239,"collectionId":null,"hidden":false,"downloadFormat":"gmaextract","autodownload":false}`

_Originally posted by @Be1zebub in https://github.com/SegoCode/swd/issues/4#issuecomment-1016665599_

**Comment by SegoCode** [comment]
@Be1zebub sounds interesting, I think all the files of the workshop come in `.zip`? the `.gma ` file will be inside the zip, I suppose. Where you found the `gmaextract` parameter in steamworkshopdownloader.io? if I implement that input parameter I would like to add all options in the readme like `gmaextract` `raw` . . . 

Any way auto-decompress the download zip I think it wouldnt be too useful, what do you think?

**Comment by Be1zebub** [comment]
the `steamworkshopdownloader.io` with the `downloadFormat:"raw"` payload param downloads the `.zip` archive with `.gma` file inside.
`.gma` is a special format that is used for addons in Garrys mod, in fact it is just a `.zip` with `LZMA` compression and some metadata (maybe it contains something else, im not sure).
if you change `downloadFormat` from `raw` to `gmaextract`, then `steamworkshopdownloader.io` will download `.gma` from the gmod steam workshop, then extract downloaded file contents and put it in `.zip` archive.
thus, when downloading, you will receive real addon files packed in `.zip` archive, not an `.gma` archive in the `.zip` archive as you got with `downloadFormat:"raw"`.
I suggest adding the feature to pass your own args to the request payload.
something like: `swd https://steamcommunity.com/sharedfiles/filedetails/?id=2456881554 --downloadFormat gmaextract --hidden false`

it would also be cool if swd recognized workshop ids with several patterns:
https://steamcommunity.com/sharedfiles/filedetails/?id=XXXXX
https://steamcommunity.com/sharedfiles/filedetails/*/XXXXX
https://steamcommunity.com/sharedfiles/filedetails/XXXXX
XXXXX

> Where you found the `gmaextract` parameter in steamworkshopdownloader.io?   
   
in chrome dev tools requests log

**Comment by SegoCode** [comment]
I have been test the option to extract in steamworkshopdownloader.io

![Screenshot 2022-01-20 at 21-37-16 Steam Workshop Downloader IO](https://user-images.githubusercontent.com/35817798/150418897-4a722bcd-146d-4c98-be54-2bf0fc389314.png)

Test with several games, all send `raw` parameter except  Garry's Mod, looking at the changelog, I see this:

`February 2, 2020 - A Small Update:
Fixed GMA Extraction for Files Uploaded After The Latest Garry's Mod Update.`

It may only exist the parameter extration for Garry's Mod?

**Comment by Be1zebub** [comment]
idk about other games, but I think that some of them also have specific formats for storing addons.

**Comment by SegoCode** [comment]
check [new release](https://github.com/SegoCode/swd/releases/tag/1.5), added `--downloadFormat` for optional parameter 👌
I keep this issue open for new parameter suggestions.
