### ISSUE TITLE
GAME NOT AVAILABLE OR SERVER IS DOWN, CODE RESPONSE: 504

### ISSUE THREAD

**Issue by aprt06** [SegoCode/swd#7]
Hello , I'm not sure something update on https://steamworkshopdownloader.io/

**Comment by SegoCode** [comment]
Yeah, the cool guy @nguyenvancaokyfpt fix the endpoint in #6, in a few days I will compile a new release.

**Comment by SegoCode** [comment]
https://github.com/SegoCode/swd/releases/tag/1.6

**Comment by aprt06** [comment]
Thank you very much!
